### ISSUE TITLE
Caracteres repetidos en el password

### ISSUE THREAD

**Issue by talivan00220** [raullaboriel/T1_GeneradorContrasenias#1]
https://github.com/raullaboriel/T1_GeneradorContrasenias/blob/d5a229b5818db8d518894d437f5bcf460030ee4c/main.py#L8

Debes validar antes que se excluyan los caracteres ya utilizados en la formación del password, por ejemplo si el password va formándose así: A#$F y en la siguiente vuelta del siglo aparece el carácter '#' debe omitirse e incluir otro diferente, de modo que no se repitan los caracteres en el password.

Saludos, espero me entiendas.

**Comment by raullaboriel** [comment]
Hola, ing.
Si se hace la validación para evitar los caracteres duplicados, específicamente en el bloque while ahi se valida y en dado caso que ya exista en la contraseña ese carácter se genera otro.
Quedo pendiente de su respuesta.
Saludos.

**Comment by talivan00220** [comment]
¡Cierto, ya corrí tu código y funciona genial!
